 source 'http://rubygems.org'

 gem 'capybara'
 gem 'webdrivers'
 gem 'cucumber'
 gem 'faker'
 gem 'httparty'
 gem 'pry'
 gem 'rspec'
 gem 'site_prism'
 gem 'selenium-webdriver'
 gem 'geckodriver-helper'
 gem 'chromedriver-helper'